import scrapy

class pokemonItem(scrapy.Item):
    nom_pkmn = scrapy.Field()
    nom_pkmn_us = scrapy.Field()
    num_pokedex = scrapy.Field()
    url_image = scrapy.Field()
    url_cri = scrapy.Field()
    type_1 = scrapy.Field()
    type_2 = scrapy.Field()
    taille_m = scrapy.Field()
    poids_kg = scrapy.Field()
    talent_1 = scrapy.Field()
    talent_2 = scrapy.Field()
    talent_cache = scrapy.Field()
    sexe = scrapy.Field()
    taux_de_capture = scrapy.Field()
    cycle_eclosion = scrapy.Field()
    groupe_oeuf_1 = scrapy.Field()
    groupe_oeuf_2 = scrapy.Field()
    points_effort = scrapy.Field()
    points_exp = scrapy.Field()
    exp_niv100 = scrapy.Field()
    pv = scrapy.Field()
    attaque = scrapy.Field()
    attaque_speciale = scrapy.Field()
    defense = scrapy.Field()
    defense_speciale = scrapy.Field()
    vitesse = scrapy.Field()

    
class evolutionItem(scrapy.Item):
    pre_evolution = scrapy.Field()
    evolution = scrapy.Field()
    condition = scrapy.Field()