CREATE TABLE IF NOT EXISTS Pokemons (
    nom_pkmn TEXT PRIMARY KEY,
    nom_pkmn_us TEXT,
    num_pokedex INTEGER,
    url_image TEXT,
    url_cri TEXT,
    type_1 TEXT,
    type_2 TEXT NULL, 
    taille_m TEXT,
    poids_kg TEXT,
    talent_1 TEXT,
    talent_2 TEXT NULL,
    talent_cache TEXT NULL,
    sexe TEXT NULL,
    taux_de_capture INTEGER NULL,
    cycle_eclosion INTEGER NULL,
    groupe_oeuf_1 TEXT NULL,
    groupe_oeuf_2 TEXT NULL,
    points_effort TEXT NULL,
    points_exp TEXT NULL,
    exp_niv100 TEXT NULL,
    pv INTEGER NULL,
    attaque INTEGER NULL,
    attaque_speciale INTEGER NULL,
    defense INTEGER NULL,
    defense_speciale INTEGER NULL,
    vitesse INTEGER NULL,
    GO_attaque INTEGER NULL,
    GO_defense INTEGER NULL,
    GO_resistance INTEGER NULL,
    GO_Buddy_Distance_Km INTEGER NULL,
    FOREIGN KEY (nom_pkmn) REFERENCES Evolutions(pre_evolution),
    FOREIGN KEY (nom_pkmn) REFERENCES Evolutions(evolution),
    FOREIGN KEY (nom_pkmn) REFERENCES Apprentissages(nom_pkmn),
    FOREIGN KEY (nom_pkmn) REFERENCES GO_Apprentissages(nom_pkmn),
    FOREIGN KEY (type_1) REFERENCES Types(type_pkmn),
    FOREIGN KEY (type_2) REFERENCES Types(type_pkmn),
    FOREIGN KEY (talent_1) REFERENCES Talents(talent),
    FOREIGN KEY (talent_2) REFERENCES Talents(talent),
    FOREIGN KEY (talent_cache) REFERENCES Talents(talent)
);