import scrapy

class pokemonItem(scrapy.Item):
    nom_pkmn = scrapy.Field()
    num_pokedex = scrapy.Field()
    url_image = scrapy.Field()
    type_1 = scrapy.Field()
    type_2 = scrapy.Field()
    taille_M = scrapy.Field()
    poids_kg = scrapy.Field()
    talent_1 = scrapy.Field()
    talent_2 = scrapy.Field()
    talent_cache = scrapy.Field()
    sexe = scrapy.Field()
    taux_de_capture = scrapy.Field()
    cycle_eclosion = scrapy.Field()
    groupe_oeuf_1 = scrapy.Field()
    groupe_oeuf_2 = scrapy.Field()
    points_effort = scrapy.Field()
    point_exp = scrapy.Field()
    exp_niv100 = scrapy.Field()
    pv = scrapy.Field()
    attaque = scrapy.Field()
    attaque_speciale = scrapy.Field()
    defense = scrapy.Field()
    defense_speciale = scrapy.Field()
    vitesse = scrapy.Field()
    